############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1


[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Teaching"
url = "teaching/"
weight = 4

[[main]]
weight = 5
name = "Students"
url = "students/"


[[main]]
weight = 6
name = "Activities"
hasChildren = true

  [[main]]
  parent = "Activities"
  name = "Service"
  url = "service/"
  weight = 1

  [[main]]
  parent = "Activities"
  name = "Administration"
  url = "admin/"
  weight = 2

[[main]]
  parent = "Activities"
  name = "Patents"
  url = "patents/"
  weight = 3

# CV
[[main]]
weight =7
name = "CV"
url = "cv/"




# footer menu
[[footer]]
name = "Impress"
url = "impress/"
weight = 2

# footer menu
[[footer]]
name = "Contact"
url = "contact/"
weight = 3
