baseURL = 'doschroeder.github.io'
languageCode = 'en-us'
author = 'Dominique Schröder'
copyright = '© 2023 Dominique Schröder. All Rights Reserved.'
title = 'Personal Website of Dominique Schröder'
logo_width='50px'

